### ISSUE TITLE
New Release for 2.x

### ISSUE THREAD

**Issue by neovintage** [DenisKolodin/elm-ace#4]
I wanted to use elm-github-install to install the new version of elm-ace but I'm getting an error. I can't satisfy versions. 

Can we cut a new release and/or publish this to packages.elm-lang.org?

**Comment by rofrol** [comment]
I got this too:

```
Could not find a solution:
  Unable to satisfy the following requirements:

  - `https://github.com/elm-community/list-extra (< 6.0.0)` required by `user-specified dependency`
  - `https://github.com/elm-community/list-extra (>= 5.0.0)` required by `user-specified dependency`
  - `https://github.com/elm-community/list-extra (>= 4.0.0)` required by `https://github.com/abadi199/elm-input-extra-5.1.0`
  - `https://github.com/elm-community/list-extra (< 5.0.0)` required by `https://github.com/abadi199/elm-input-extra-5.1.0`

```

**Comment by therustmonk** [comment]
I can't publish it to packages, because it contains native **JavaScript** code (elm's repository blocks native code).
I use https://github.com/NoRedInk/elm-ops-tooling to install (`/sub/` is a dir with git submodules):
```
./sub/elm-ops-tooling/elm_self_publish.py ./sub/elm-ace/ .
```

But I won't close this issue, because I want to check git installer later.

**Comment by therustmonk** [comment]
It solved! You can use `elm-github-install` with `2.1.2` version.
